project:
  type: manuscript
  output-dir: docs/
  post-render:
    - _cleanup.R

manuscript:
  article: manuscript.qmd
  notebooks:
    - notebook: notebooks/ligof.qmd
    - notebook: notebooks/dwls.qmd
    - notebook: notebooks/pml.qmd

# notebook-links: false

format:
  html:
    toc: true
    toc-location: left
    number-sections: true
    fontsize: 110%
    lightbox: true
    # page-layout: full
    grid:
      sidebar-width: 200px
      body-width: 900px
      margin-width: 0px    
    # template-partials:
    #   - title-metadata.html

  pdf:
    pdf-engine: pdflatex
    output-file: jamil2025limited
    keep-tex: true
    number-sections: true
    header-includes:
      - \include{_extensions/maths_shortcuts.tex}

  # arxiv-pdf:
  #   pdf-engine: pdflatex
  #   keep-tex: true
  #   linenumbers: true
  #   doublespacing: false
  #   runninghead: "A Preprint"
  #   authorcols: false
  #   output-file: jamil2025limited
  #   header-includes:
  #     - \usepackage{setspace}
  #     - \include{_extensions/maths_shortcuts.tex}
  #     - \onehalfspacing

  # docx: 
  #   link-citations: true
  #   output-file: jamil2025limited

execute:
  echo: false
  cache: true
  freeze: auto
  warning: false

editor:
  markdown:
    wrap: sentence
editor_options: 
  chunk_output_type: console

citation: 
  type: article-journal  
  issued: 2025
  container-title: 'Manuscript in preparation'
  url: https://haziqj.ml/ligof-tests
google-scholar: true
